### PR TITLE
Reference page

### LINKED ISSUE #589: Create reference submission page
## Description
Part of applying for an award or other event may involve the applicant seeking references from their colleagues/lecturers etc. The candidate will create reference requests when filling in their application form, and the person providing the reference (the referer) will receive an email prompting them to visit a page on Baobab to submit a reference (in the form of an uploaded PDF) for the candidate. This issue involves creating the page that a referer can use to submit this reference.

## Tasks
- Create a new page and component with a path of `reference/:token` where token is a parameter. This URL will correspond to the one sent to the referer by email. 
- Create a service with functions to get reference request details from the [ReferenceRequestDetailAPI](https://github.com/deep-learning-indaba/Baobab/blob/develop/api/app/references/api.py#L40) (might not yet have been created, see #591 , if that's the case, you can just use some dummy data for now), and POST completed references to the [ReferenceAPI](https://github.com/deep-learning-indaba/Baobab/blob/bf99909f71ef7cca4923d3a93ddcea9e6d443ccf/api/app/references/api.py#L128)
- Check the `is_application_open` flag in the ReferenceRequestDetail response. If it is `false`, display an error message saying that applications are now closed and no more references are being accepted. Prompt them to email the event organisers with a mailto link to the `email_from` address returned with the reference request details. 
- Display the candidate's title, firstname, lastname with some text along the lines of "CANDIDATE has requested your reference for their application to the <event_name>. Kindly upload your reference in the form of a PDF below."
- Add a [FileUpload](https://github.com/deep-learning-indaba/Baobab/blob/develop/webapp/src/components/form/FormFileUpload.js) component that accepts a PDF file and uploads it to the File API. You can find a wrapper component that handles the upload in the [registration form component](https://github.com/deep-learning-indaba/Baobab/blob/ed9ef8986eeb5d725ce24cffdbbec15b7224c83a/webapp/src/pages/registration/components/RegistrationComponent.js#L20) - so move this to a common location and reuse it. Bonus points for also cleaning up the [ApplicationForm](https://github.com/deep-learning-indaba/Baobab/blob/ed9ef8986eeb5d725ce24cffdbbec15b7224c83a/webapp/src/pages/applicationForm/components/ApplicationForm.js#L47) to use this component too!
- Add a SUBMIT button which sends the reference token and the uploaded_document reference (a GUID that gets returned by the file API when uploading the file) to the [ReferenceAPI](https://github.com/deep-learning-indaba/Baobab/blob/bf99909f71ef7cca4923d3a93ddcea9e6d443ccf/api/app/references/api.py#L128). Endpoint: `/api/v1/reference`
- Disable the submit button and/or display an error if the user hasn't uploaded a file
- If the user has already submitted a reference (the `reference_submitted_timestamp` on the reference request details response is not NULL), display a message stating that they have already uploaded a reference on <reference_submitted_timestamp>, but they can update their reference. If this is the case, send the updated reference information to the PUT method of the reference API

## Definition of Done
- Functionality has been tested manually
- PR created to merge into develop branch, reviewed and review comments addressed

### LINKED ISSUE #644: Make FileUpload work in dev mode
Currently the file upload component doesn't work in development mode (running locally), probably because it tries to use dummy Google Cloud Storage credentials. Change this to upload to some local directly instead.

### LINKED ISSUE #649: Date picker component doesn't display selected date
After selecting a date on the [date picker form control](https://github.com/deep-learning-indaba/Baobab/blob/develop/webapp/src/components/form/FormDate.js), the control remains blank and does not show the selected date. Eg. see this screenshot where I have selected a date:

Screen Shot 2020-03-31 at 21 24 05

The selected date does appear when clicking on the calendar icon though:
Screen Shot 2020-03-31 at 21 25 46

It also seems to set the value in the answer to a date object (rather than a string) which then can't be displayed in the confirmation screen

### PR DESCRIPTION
**Pull request by avishkar58**
Resolves #589 
Resolves #644 
Resolves #649 

Apologies for the large PR, it also includes some cleanup and refactoring.

### CODE REVIEW

File: webapp/src/pages/applicationForm/components/ApplicationForm.js [hunk 1]
```diff
@@ -54,7 +54,7 @@ class FieldEditor extends React.Component {
   handleChange = event => {
     // Some components (datepicker, custom controls) return pass the value directly rather than via event.target.value
     const value = event && event.target ? event.target.value : event;
-
+    console.log('Value changed to: ' + value);
```
Comment (KaleabTessera) [inline webapp/src/pages/applicationForm/components/ApplicationForm.js:57]: Please remove forgotten console.log.
