### PR TITLE
Fixed typo preventing error from being displayed

### LINKED ISSUE #169: Password reset is not sending reset email
Julien just tried signing up and the password reset didn't send a link

### PR DESCRIPTION
**Pull request by avishkar58**
I think this will fix #169 - but let's leave that open until we confirm.

### CODE REVIEW

File: webapp/src/pages/resetPassword/components/RequestPasswordResetForm.js [hunk 1]
```diff
@@ -28,18 +28,19 @@ class RequestPasswordResetForm extends Component {
...
     userService.requestPasswordReset(this.state.email).then(response => {
-      console.log("Response from user service: ", response);
       if (response.status === 201) {
         this.setState({
           resetRequested: true
-        })
+        });
       } else {
         this.setState({
-          error: response.messsage,
```
Comment (jaderabbit) [inline webapp/src/pages/resetPassword/components/RequestPasswordResetForm.js]: This is why I hate javascript :P
